New branch
YurySuvalau/AutomationPractice pull request #1
Opened 2021-03-07 14:16 UTC by YurySuvalau

2021-03-07 16:40 UTC, vchesnakoutest requested changes
please make fixes

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/AddedProductModalPage.java
> +    @Step("Click to Proceed to Checkout")
давай указывать, где именно происходит действие:
Click to Proceed to Checkout on 'Added Product' modal например

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/AddressCheckoutPage.java
> +    @Step("Click to Proceed to Checkout")
указывем, где именно происходит действие

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/BankWirePaymentPage.java
> +    private static final By I_CONFIRM_MY_ORDER_BTN = By.xpath("//*[@class='button btn btn-default button-medium']");
тут в class используется несколько классов, попробуй не привязываться сразу ко всем, а использовать:
//*[contains(@class, 'button-medium')] - проверь работает или нет

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/BankWirePaymentPage.java
> +    @Step("Click to Confirm my order")
указывем, где именно происходит действие

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/BankWirePaymentPage.java
> +    public OrderConfirmationPage clickOnIConfirmMyOrder() {
clickOnIConfirmMyOrderButton

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    private static final By PROCEED_TO_CHECKOUT_BTN = By.xpath("//*[@class='button btn btn-default standard-checkout button-medium']");
тоже попробуй не привязываться сразу ко всем классам, может standard-checkout будет работать

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    private static final By QUANTITY_INPUT = By.xpath("//*[@class='cart_quantity_input form-control grey']");
также не привязываемся ко всем классам

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    private static final By ITEM_NAME_BLOUSE = By.xpath("//*[contains(@class,'cart_item ')]//*[contains(text(),'Blouse')]");
не хардкодай какие-то товары в локаторах. используй String.format и передавай текст через параметр в методе getItemName

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    private static final By ADD_QUANTITY_BUTTON = By.xpath("//*[@class='cart_quantity_up btn btn-default button-plus']");
также не привязываемся ко всем классам

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    private static final By DISCOUNT = By.xpath("//*[@class='price-percent-reduction small']");
укажи в имени, что это за элемент  DISCOUNT - тайтл, сообщение или ещё что-то

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    private static final By EMPTY_CART_MESSAGE = By.xpath("//*[@class='alert alert-warning']");
также не привязываемся ко всем классам

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    private static final By SHIPPING_CART_CONTAINS_2_LABEL = By.xpath("//*[@id='summary_products_quantity'][text()='2 Products']");
не хардкодай значение "2" в локаторе, используй String.format и передавай значение через параметр в методе getDiscount и тд

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @Step("Get product name")
указывем, где именно происходит действие

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public String getItemName() {
передаем название как параметр в методе

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @Step("Get product unit price")
указывем, где именно происходит действие

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @Step("Get product quantity")
указывем, где именно происходит действие

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @Step("Click to Add quantity button")
указывем, где именно происходит действие

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @Step("Get discount")
указывем, где именно происходит действие

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +            Assert.fail(String.format("Label contains 1 product is not displayed! Locator: '%s' was not found!", SHIPPING_CART_CONTAINS_2_LABEL));
также в сообщение передавай сколько продуктов ты ждал

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @Step("Click on delete button")
указывем, где именно происходит действие

и дальше во всех аналогичных степах (укзаываем название страницы \ модала где это действие происходит)

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    @Step("Get cat empty message")
cat - опечатка

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public String getTotalPrice() {
тоже передаем в метод значение для локатора

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CategoryPage.java
> +    private static final By LOADING_LOGO = By.xpath("//*[@class='product_list grid row']//*[@src='http://automationpractice.com/img/loader.gif']");
скорее всего в src тоже можно сделать через contains(@src, 'loader.gif')

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CategoryPage.java
> +    public CategoryPage selectColorWhiteInFilter() {
передавай цвет как параметр. и если тут от цвета зависит локатор layered_id_attribute_group_8 - то меняй локатор через String.format (например для белого в конце будет 8, для другого цвета другое значение и тд). Логику какому цвету какое значение присвоить можно делать в этом же методе

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CategoryPage.java
> +    public boolean isDisplayedLoadingLogo() {
isLoadingLogoDisplayed

2021-03-07 16:40 UTC, vchesnakoutest commented on src/main/java/pages/CategoryPage.java
> +    public CategoryPage clickCasualDressSubcategory() {
тоже самое, не хардкодай значения, передавай как параметр

2021-03-07 16:40 UTC, vchesnakoutest commented on src/test/java/Utils/CapabilitiesGenerator.java
> +package Utils;
название пакетов с маленькой буквы

2021-03-07 16:40 UTC, vchesnakoutest commented on src/test/java/Utils/CapabilitiesGenerator.java
> +//        }
если ты используешь webdrivermanager эта логика не нужна (старайся не оставлять закоменченный код, а если оставляешь пиши коммент, почему код закомменчен)

2021-03-07 16:40 UTC, vchesnakoutest commented on src/test/java/Utils/CapabilitiesGenerator.java
> +        //options.addArguments("--disable-gpu"); //https://stackoverflow.com/questions/51959986/how-to-solve-selenium-chromedriver-timed-out-receiving-message-from-renderer-exc
тоже самое

2021-03-07 16:40 UTC, vchesnakoutest commented on src/test/java/test_data/TestConstants.java
> +    String PASSWORD = "123456tester";
пока ок, но потом надо будет в property file это вынести

2021-03-07 16:40 UTC, vchesnakoutest commented on src/test/java/tests/CartTest.java
> +        Assert.assertEquals(cartPage.getUnitQuantity(), "1");
вообще было бы круто написать объект продукта, с необходимыми параметрами, и просто сетать ему значения.
например.
Product product = new Product
product.setPrice("$27.00") и тд

а потом в ассертах уже с этого продукта берешь данные , например
product.getPrice и тд

а сами продукты можно создавать где-то в отдельном классе с тестовыми данными например

2021-03-07 16:40 UTC, vchesnakoutest commented on src/test/java/tests/LoginTest.java
> +        Assert.assertEquals(mainPage.getUrl(), "http://automationpractice.com/index.php?controller=my-account");
"http://automationpractice.com/index.php?controller=my-account" - тоже надо куда-то в константы вынести

2021-03-07 18:50 UTC, YurySuvalau commented on src/main/java/pages/AddedProductModalPage.java
> +    @Step("Click to Proceed to Checkout")
Исправил

2021-03-07 18:50 UTC, YurySuvalau commented on src/main/java/pages/AddressCheckoutPage.java
> +    @Step("Click to Proceed to Checkout")
Исправил

2021-03-07 18:50 UTC, YurySuvalau commented on src/main/java/pages/BankWirePaymentPage.java
> +    private static final By I_CONFIRM_MY_ORDER_BTN = By.xpath("//*[@class='button btn btn-default button-medium']");
Исправил

2021-03-07 18:50 UTC, YurySuvalau commented on src/main/java/pages/BankWirePaymentPage.java
> +    @Step("Click to Confirm my order")
Исправил

2021-03-07 18:50 UTC, YurySuvalau commented on src/main/java/pages/BankWirePaymentPage.java
> +    public OrderConfirmationPage clickOnIConfirmMyOrder() {
Исправил

2021-03-07 18:51 UTC, YurySuvalau commented on src/test/java/Utils/CapabilitiesGenerator.java
> +//        }
Убрал лишний код

2021-03-07 18:51 UTC, YurySuvalau commented on src/test/java/Utils/CapabilitiesGenerator.java
> +        //options.addArguments("--disable-gpu"); //https://stackoverflow.com/questions/51959986/how-to-solve-selenium-chromedriver-timed-out-receiving-message-from-renderer-exc
Убрал лишний код

2021-03-08 08:12 UTC, YurySuvalau commented on src/test/java/test_data/TestConstants.java
> +    String PASSWORD = "123456tester";
сделал

2021-03-08 13:08 UTC, YurySuvalau commented on src/test/java/tests/LoginTest.java
> +        Assert.assertEquals(mainPage.getUrl(), "http://automationpractice.com/index.php?controller=my-account");
Есть такое в константах, вынес в exspectedResult

2021-03-08 20:00 UTC, YurySuvalau commented on src/test/java/tests/CartTest.java
> +        Assert.assertEquals(cartPage.getUnitQuantity(), "1");
Сделал

2021-03-10 14:31 UTC, vchesnakoutest requested changes
please make fixes

2021-03-10 14:31 UTC, vchesnakoutest commented on .allure/allure-2.8.1/lib/config/log4j.properties
> +log4j.logger.org.mortbay.log = INFO
удалить весь пакет

2021-03-10 14:31 UTC, vchesnakoutest commented on pom.xml
> +            <version>1.18.18</version>
вынесем в properties

2021-03-10 14:31 UTC, vchesnakoutest commented on src/main/java/constants/Constants.java
> +    String URL = "http://automationpractice.com/";
BASE_URL, AUTO_PRACTICE_URL

2021-03-10 14:31 UTC, vchesnakoutest commented on src/main/java/object/Item.java
> +    private String itemTwoQuantity;
удалить и использовать itemQuantity

2021-03-10 14:31 UTC, vchesnakoutest commented on src/main/java/object/Item.java
> +    private String productCountFiveItem;
тоже самое, не харкодать кол-во продуктов

2021-03-10 14:31 UTC, vchesnakoutest commented on src/main/java/pages/BankWirePaymentPage.java
> +    private static final By ORDER_SUM = By.xpath("//*[@class='box cheque-box']//span[@class='price']");
//*[@class='box cheque-box'] - попробуй будет ли работать через contains:

//*[contains(@class, 'cheque-box')]

2021-03-12 16:31 UTC, vchesnakoutest approved these changes

2021-03-13 04:45 UTC, merged